In [2]:
import twogroup_linalg.twogroup_linalg as lin
#import third_order_gates.z248_linalg as z248lin
import numpy as np

In [2]:
siz = 5
M1 = np.random.randint(0,16,size=(siz, siz))
M2 = np.random.randint(0,16,size=(siz, siz))
M1_mod = lin.mod_matrix.from_numpy(M1, 4)
M2_mod = lin.mod_matrix.from_numpy(M2, 4)
Mmod_prod = M1_mod.product(M2_mod, 3)
print((M1@M2) % 16 - Mmod_prod.to_numpy())

[[0 8 8 8 0]
 [0 0 0 0 0]
 [0 8 8 0 0]
 [0 0 8 8 0]
 [0 8 0 0 0]]


In [13]:
siz = 3000
M1 = np.random.randint(0,2,size=(siz, siz))
M2 = np.random.randint(0,2,size=(siz, siz))
M1_mod = lin.mod_matrix.from_numpy(M1, 1)
M2_mod = lin.mod_matrix.from_numpy(M2, 1)
%time Mmod_prod = M1_mod.product(M2_mod, 1)
#%time M_prod = M1 @ M2

CPU times: user 3.87 s, sys: 995 μs, total: 3.87 s
Wall time: 3.87 s


In [8]:
siz = 3000
M1 = np.random.randint(0,2,size=(siz, siz))
M2 = np.random.randint(0,2,size=(siz, siz))
M1bit = lin.z2lin.numpy_to_bitgauss(M1)
M2bit = lin.z2lin.numpy_to_bitgauss(M2)
%time m1m2 = lin.mul_mod(M1bit, M2bit, 3)
%time prod = M1bit @ M2bit
%time Mprod = M1 @ M2
#print(M1@M2 - m1m2.to_numpy())

CPU times: user 14.2 s, sys: 10 ms, total: 14.2 s
Wall time: 14.2 s
CPU times: user 1.41 s, sys: 6.99 ms, total: 1.42 s
Wall time: 1.42 s
CPU times: user 32.9 s, sys: 8.98 ms, total: 32.9 s
Wall time: 32.9 s


In [4]:
siz = 2000
M1 = np.random.randint(0,2,size=(siz, siz))
M2 = np.random.randint(0,2,size=(siz, siz))
%time M = M1 @ M2
M1 = np.random.randint(0,2,size=(siz, siz), dtype= np.uint8)
M2 = np.random.randint(0,2,size=(siz, siz), dtype= np.uint8)
%time M = M1 @ M2
M1bit = lin.z2lin.numpy_to_bitgauss(M1)
M2bit = lin.z2lin.numpy_to_bitgauss(M2)
%time M = M1bit @ M2bit

CPU times: user 15.8 s, sys: 5.02 ms, total: 15.8 s
Wall time: 15.8 s
CPU times: user 3.58 s, sys: 16 μs, total: 3.58 s
Wall time: 3.58 s
CPU times: user 469 ms, sys: 4 μs, total: 469 ms
Wall time: 468 ms
