In [1]:
import numpy as np
import third_order_gates.z248_linalg as lin
import z248_kernel_snf as snf

# Testing z234_hom class

Random, tostring, and composition

In [2]:
x = lin.z248_hom.rand((2,3,4),(3,4,5))
y = lin.z248_hom.rand((3,4,5),(4,6,5))
xy = x @ y
print(x.tostring())
print(y.tostring())
print(xy.tostring())

0 1 0 | 0 0 1 0 | 0 1 0 0 1 
1 0 0 | 1 1 0 0 | 1 1 0 0 0 
------+---------+-----------
1 1 0 | 3 1 3 1 | 0 2 0 1 1 
0 1 1 | 0 0 1 3 | 1 1 2 0 3 
1 0 0 | 3 1 1 0 | 1 2 3 0 0 
------+---------+-----------
0 0 0 | 2 1 0 2 | 7 4 6 4 2 
1 0 0 | 2 1 1 3 | 3 2 7 7 3 
1 1 1 | 1 2 3 1 | 7 4 0 1 1 
1 1 1 | 1 0 1 3 | 3 0 5 4 4 

0 1 0 1 | 0 0 1 1 1 0 | 1 0 0 1 1 
1 0 1 1 | 0 0 1 0 1 1 | 1 1 1 0 1 
0 0 0 1 | 1 1 0 1 1 1 | 1 0 1 1 0 
--------+-------------+-----------
1 0 0 1 | 3 3 1 1 1 2 | 1 2 3 0 0 
0 0 1 0 | 2 0 1 1 1 0 | 2 2 3 0 0 
1 1 1 1 | 1 3 1 3 0 2 | 1 1 0 1 3 
1 1 1 1 | 3 2 3 0 1 2 | 3 0 1 2 1 
--------+-------------+-----------
1 0 1 0 | 3 2 1 1 0 3 | 3 6 7 7 5 
0 0 1 1 | 3 0 2 2 2 2 | 7 6 0 4 2 
1 0 0 1 | 2 0 3 3 1 0 | 3 2 2 7 0 
1 1 0 0 | 3 0 0 1 3 0 | 7 6 7 1 7 
1 1 0 1 | 3 0 2 3 1 0 | 7 4 3 5 3 

1 0 1 1 | 1 1 0 1 1 1 | 0 0 0 0 1 
0 1 0 1 | 1 1 1 1 1 0 | 0 0 1 0 0 
--------+-------------+-----------
0 1 0 1 | 1 0 2 3 1 0 | 3 3 1 1 0 
1 0 1 0 | 2 3 2 1 1 2 | 3 3 3 1 0 
0 0 0 1 | 2 0 

## Testing z248_z2_kernel

In [4]:
dim1 = (3,3,3)
dim0 = 4
hom = np.random.randint(0,2,size=(dim0,dim1[0]+dim1[1]+dim1[2]))
print("hom\n", hom)
ker = lin.z248_z2_kernel(hom, dim1)
print(ker.tostring())
fullhom = lin.z248_hom(hom, (dim0,0,0), dim1)
print((fullhom@ker).tostring())

hom
 [[1 0 1 1 0 1 0 0 0]
 [0 1 1 1 0 0 0 1 0]
 [1 1 1 0 1 1 0 1 0]
 [0 0 1 1 0 0 0 0 0]]
0 | 0 1 | 0 0 0 
0 | 0 0 | 0 1 0 
0 | 1 0 | 0 0 0 
--+-----+-------
1 | 1 0 | 0 0 0 
0 | 1 0 | 0 0 0 
0 | 0 1 | 0 0 0 
--+-----+-------
0 | 0 0 | 1 0 0 
0 | 0 0 | 0 1 0 
0 | 0 0 | 0 0 1 

0 | 0 0 | 0 0 0 
0 | 0 0 | 0 0 0 
0 | 0 0 | 0 0 0 
0 | 0 0 | 0 0 0 
--+-----+-------
--+-----+-------



## test if kernel vectors multiply to zero for filtration

In [3]:
for i in range(100):
    A = lin.z248_hom.rand_dim(10)
    ker = A.kernel()
    print(f"{A.dim0} x {A.dim1}: {(A@ker).is_zero()}")

[1 6 6] x [2 3 2]: True
[5 6 7] x [3 5 6]: True
[1 6 3] x [8 8 9]: True
[1 0 4] x [5 9 9]: True
[3 8 6] x [7 5 2]: True
[6 6 0] x [0 7 6]: True
[9 0 8] x [8 1 9]: True
[9 1 6] x [8 3 4]: True
[8 8 5] x [0 4 1]: True
[7 5 5] x [6 5 3]: True
[8 6 5] x [9 6 5]: True
[7 0 5] x [6 5 3]: True
[5 6 6] x [4 8 8]: True
[9 3 9] x [0 8 5]: True
[7 8 8] x [1 3 9]: True
[7 6 4] x [5 2 8]: True
[7 4 3] x [4 8 7]: True
[9 8 8] x [3 2 7]: True
[3 0 3] x [7 1 1]: True
[1 3 3] x [7 2 5]: True
[1 6 0] x [1 3 0]: True
[1 8 0] x [4 2 5]: True
[2 6 7] x [2 2 3]: True
[5 9 9] x [3 2 0]: True
[7 0 5] x [5 9 3]: True
[8 4 6] x [4 0 5]: True
[3 8 1] x [0 5 1]: True
[3 5 3] x [9 9 4]: True
[8 3 1] x [1 8 6]: True
[1 4 2] x [0 5 7]: True
[6 4 1] x [4 4 3]: True
[7 2 6] x [8 9 5]: True
[9 4 0] x [8 6 6]: True
[2 3 4] x [7 3 5]: True
[2 0 1] x [3 7 9]: True
[7 7 0] x [9 3 9]: True
[0 3 6] x [2 8 5]: True
[8 9 9] x [6 0 0]: True
[2 9 5] x [5 2 1]: True
[0 4 3] x [1 5 9]: True
[7 9 7] x [7 5 2]: True
[0 6 2] x [0 5 1

## Test for snf kernel method

In [4]:
for i in range(100):
    A = lin.z248_hom.rand_dim(7)
    try:
        ker = snf.z248_z248_kernel(A)
        print(f"{A.dim0} x {A.dim1}: {(A@ker).is_zero()}")
    except:
        print(f"{A.dim0} x {A.dim1}: Snf kernel method overflow")

[5 0 5] x [4 3 2]: True
[1 2 6] x [1 2 0]: True
[4 2 1] x [4 6 4]: True
[4 1 0] x [6 4 1]: True
[2 4 5] x [3 5 4]: True
[1 3 0] x [3 1 0]: True
[2 3 4] x [1 5 1]: True
[2 5 2] x [0 6 1]: True
[3 6 5] x [4 0 6]: Snf kernel method overflow
[5 1 5] x [3 4 2]: True
[2 2 4] x [4 0 0]: True
[0 4 3] x [1 0 4]: True
[6 5 6] x [4 0 2]: True
[4 1 6] x [2 4 6]: Snf kernel method overflow
[3 5 6] x [3 4 6]: True
[0 1 3] x [6 2 2]: True
[4 1 3] x [0 6 2]: True
[2 1 6] x [4 0 6]: Snf kernel method overflow
[0 1 3] x [6 0 4]: True
[0 5 6] x [2 2 0]: True
[6 6 3] x [2 6 0]: Snf kernel method overflow
[3 2 2] x [3 2 3]: True
[5 4 0] x [3 6 0]: True
[1 4 3] x [1 6 0]: True
[1 3 0] x [4 3 3]: True
[1 4 0] x [5 2 1]: True
[2 3 2] x [6 0 5]: Snf kernel method overflow
[5 5 0] x [5 1 3]: True
[5 3 5] x [6 5 1]: Snf kernel method overflow
[2 6 3] x [5 3 2]: True
[6 1 3] x [6 6 6]: Snf kernel method overflow
[6 5 0] x [0 6 2]: True
[6 0 6] x [2 5 2]: True
[2 3 0] x [6 6 3]: True
[4 6 0] x [0 4 0]: True
[2 6 5

## Test if filtration and snf kernel have the same dimensions (form same groups)

In [11]:
for i in range(100):
    A = lin.z248_hom.rand_dim(5)
    ker_filt = A.kernel()
    try:
        ker_snf = snf.z248_z248_kernel(A)
        print(f"{A.dim0} x {A.dim1}: {ker_filt.dim1 == ker_snf.dim1}")
    except:
        print(f"{A.dim0} x {A.dim1}: Snf kernel method overflow")

[2 1 0] x [3 3 4]: True
[1 4 4] x [2 4 0]: True
[0 4 0] x [3 3 4]: True
[0 2 4] x [0 3 2]: True
[0 1 3] x [0 1 3]: True
[4 4 1] x [3 0 4]: True
[3 1 4] x [4 4 3]: Snf kernel method overflow
[4 4 3] x [1 2 3]: True
[3 2 2] x [3 2 4]: True
[0 4 3] x [1 4 0]: True
[3 4 3] x [3 4 3]: True
[4 4 1] x [2 2 4]: True
[2 0 0] x [2 3 1]: True
[2 3 4] x [2 1 4]: True
[0 1 3] x [2 3 3]: True
[4 2 2] x [0 0 1]: True
[3 2 1] x [2 2 3]: True
[0 2 0] x [0 1 3]: True
[3 3 1] x [3 1 0]: True
[3 3 3] x [2 0 0]: True
[0 4 0] x [4 0 4]: True
[3 0 2] x [0 3 1]: True
[2 0 0] x [2 0 3]: True
[2 4 2] x [4 0 2]: True
[4 3 2] x [4 1 0]: True
[0 3 2] x [3 0 2]: True
[4 0 0] x [2 3 0]: True
[2 1 1] x [3 2 4]: True
[4 0 0] x [4 1 0]: True
[1 1 0] x [3 0 4]: True
[4 0 1] x [1 0 4]: True
[3 3 2] x [2 4 1]: True
[2 4 0] x [3 1 2]: True
[3 3 2] x [1 1 4]: True
[4 4 3] x [1 1 4]: True
[0 1 4] x [1 1 3]: True
[4 2 4] x [0 4 1]: True
[2 0 4] x [1 1 4]: True
[4 0 3] x [3 0 1]: True
[2 4 0] x [2 4 3]: True
[1 3 3] x [4 1 4]:

## Testing if z248_solve_helper does indeed yield a solution

In [4]:
for i in range(100):
    X = lin.z248_hom.rand_dim(5)
    k_to_find = lin.z248_elem.rand(X.dim1)
    #b = lin.z248_elem.rand(X.dim0)
    b = X @ k_to_find
    ker, helper = X.kernel(return_solve_helper = True)
    try:
        k = lin.z248_solve_with_helper(X, b, helper)
        print(f"Xk=b:{(X @ k - b).is_zero()}")
    except:
        print("Solution not found!?")

Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True
Xk=b:True


## Testing epi-mono decomposition

In [9]:
for i in range(1000):
    X = lin.z248_hom.rand_dim(5)
    L, R = lin.z248_epi_mono(X)
    Lker = L.kernel()
    Xker = X.kernel()
    X_coker_dim = X.dim1[0]+2*X.dim1[1]+3*X.dim1[2] - (Xker.dim1[0]+2*Xker.dim1[1]+3*Xker.dim1[2])
    X_img_dim = L.dim1[0]+2*L.dim1[1]+3*L.dim1[2]
    print(f"LR=X:{(L @ R - X).is_zero()}, L injective: {Lker.dim1 == (0,0,0)}, Cokernel dim = Image dim: {X_coker_dim == X_img_dim}")

LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: True, Cokernel dim = Image dim: True
LR=X:True, L injective: 