In [1]:
import twogroup_linalg
import twogroup_linalg.z2_helpers as z2lin
import twogroup_linalg.bitgauss_wrappers as bitwrap
import numpy as np
import bitgauss as bg

## Test solving Z2 linear equations with helpers

In [4]:
for i in range(1000):
    shape = np.random.randint(0,10,size=(2,))
    A = np.random.randint(0,2,size=shape)
    sol_to_find = np.random.randint(0,2,size=(A.shape[1],))
    b = A @ sol_to_find
    help = z2lin.get_solve_helper(A)
    try:
        sol = z2lin.solve_with_helper(*help, b)
        print(np.all((A @ sol - b) % 2 == 0))
    except:
        print("Solution not found!")

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


## Testing bitgauss functions

In [ ]:
import third_order_gates.bitgauss_wrappers as bitg
import third_order_gates.galois_wrappers as galo
for i in range(20):
    dim0, dim1 = np.random.randint(0,5,size=(2,))
    mat = np.random.randint(0,2,size=(dim0, dim1))
    gauss_ker = bitg.kernel(mat)
    gauss_ker_test = np.all((mat @ gauss_ker) % 2 == 0)
    galois_ker = galo.kernel(mat)
    kernel_dims_same = gauss_ker.shape[0] == galois_ker.shape[0]
    print(f"bitgauss kernel test: {gauss_ker_test}, kernel dimension equal to galois kernel: {kernel_dims_same}")


bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dimension equal to galois kernel: True
bitgauss kernel test: True, kernel dim

In [ ]:
for i in range(20):
    dim0, dim1 = np.random.randint(0,5,size=(2,))
    mat = np.random.randint(0,2,size=(dim0, dim1))
    gauss_red = bitg.rref(mat)
    galois_red = galo.rref(mat)
    row_reduction_same = np.all(gauss_red - galois_red == 0)
    print(f"bitgauss and galois yield same row reduction: {row_reduction_same}")

bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same row reduction: True
bitgauss and galois yield same 

## testing bitgauss mul_carries method

In [41]:
M1 = np.random.randint(0,2,size=(5,30))
M1bit = bitwrap.numpy_to_bitgauss(M1)
M2 = np.random.randint(0,2,size=(30,6))
M2bit = bitwrap.numpy_to_bitgauss(M2)
M_list = bg.BitMatrix.mul_carries(M1bit, M2bit, 3)
M_int = sum([int(2**i) * bitwrap.bitgauss_to_numpy(mbit) for i, mbit in enumerate(M_list)])
print(M_int - M1 @ M2)

[[-8 -8 -8 -8 -8 -8]
 [-8 -8 -8 -8 -8 -8]
 [ 0 -8  0  0  0  0]
 [-8 -8 -8  0  0  0]
 [ 0 -8 -8  0  0  0]]


## speed comparison for mul_carry and numpy mul
mul_carry is much faster than numpy mul, even for 10 carries
mul_carry with one carry is 3-4 times slower than mod2 bitmatrix multiplication, which isn't ideal

In [6]:
siz = 10000
M1 = np.random.randint(0,2,size=(siz, siz))
M1bit = bitwrap.numpy_to_bitgauss(M1)
M2 = np.random.randint(0,2,size=(siz, siz))
M2bit = bitwrap.numpy_to_bitgauss(M2)
%time M12bit = M1bit @ M2bit
%time M_list = bg.BitMatrix.mul_carries(M1bit, M2bit, 1)
#%time M_list = bg.BitMatrix.mul_carries(M1bit, M2bit, 10)
#%time M12 = M1 @ M2

CPU times: user 3.83 s, sys: 37.1 ms, total: 3.87 s
Wall time: 3.86 s
CPU times: user 13.3 s, sys: 34.2 ms, total: 13.3 s
Wall time: 13.3 s


In [2]:
siz = 5
M1 = np.random.randint(0,2,size=(siz, siz))
M1bit = bitwrap.numpy_to_bitgauss(M1)
M2 = np.random.randint(0,2,size=(siz, siz))
M2bit = bitwrap.numpy_to_bitgauss(M2)
Mbit_sum = M1bit & M2bit
print(M1)
print(M2)
print(bitwrap.bitgauss_to_numpy(Mbit_sum))
print(M1bit[2:4,2:4])

[[1 1 1 0 1]
 [1 0 0 0 1]
 [0 1 0 0 0]
 [1 1 0 1 0]
 [1 0 1 1 1]]
[[0 0 1 1 0]
 [0 0 0 1 0]
 [1 1 1 1 1]
 [0 1 1 1 0]
 [1 0 0 0 0]]
[[0 0 1 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [1 0 0 0 0]]


ValueError: Invalid index type

## Testing stagger_kernel()

In [ ]:
A = np.random.randint(2, size=(2,8))
ker, kerdims = lin.stagger_kernel(A, (3,0,5))
print(kerdims)
print(ker)
print(A@ker % 2)

[1, 0, 5]
[[0 0 0 0 1 0]
 [0 0 1 1 1 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


## Testing image completion

In [ ]:
for i in range(20):
    dim = np.random.randint(7, size=(2,))
    A = np.random.randint(2, size=dim)
    B = lin.image_completion(A)
    AB = np.hstack([A,B])
    kerA = bitg.kernel(A.T)
    kerAB = bitg.kernel(AB.T)
    print(kerA.shape[1] == B.shape[1], kerAB.shape[1] == 0)

True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
True True
